version: "1.0"
info:
  model: int-scaffold
packages:
- name: ListenerUpgradeProject
  gitServerName: BTShared
  gitUrl: https://github.com/Bharathi-Thammisetty-IBM
  gitUsername: Bharathi-Thammisetty-IBM
  gitBranch: main
